<?php

namespace CharacterBundle\Repository\Ability;

/**
 * OwnedAbilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OwnedAbilityRepository extends \Doctrine\ORM\EntityRepository
{
}
