<?php

namespace CharacterBundle\Repository\Aptitude;

/**
 * AptitudeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AptitudeRepository extends \Doctrine\ORM\EntityRepository
{
}
