<?php

namespace CharacterBundle\Repository\Aptitude;

/**
 * AptitudeValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AptitudeValueRepository extends \Doctrine\ORM\EntityRepository
{
}
